#!/bin/bash
cd "$(dirname "$(readlink -f "$0")")"

# CHECK IF SD HAS BEEN CLONED !
DRIVE=$(findmnt -n -o SOURCE --target /)
DRIVE_ID=$(udevadm info --name=$DRIVE | grep ID_SERIAL= | cut -d '=' -f2)
LAST_DRIVE_ID=$(cat /data/var/drive-id)

if [[ $DRIVE_ID == $LAST_DRIVE_ID ]]
        then
                echo "drive-id is valid"
        else
                echo "drive-id has changed, i am a clone !"
                echo $DRIVE_ID > /data/var/drive-id

                echo "extending FS"

                # target disk
                if (ls /dev/mmcblk0 > /dev/null 2>&1); then
                        disk='mmcblk0'
                elif (ls /dev/mmcblk1 > /dev/null 2>&1); then
                        disk='mmcblk1'
		elif (ls /dev/sda > /dev/null 2>&1); then
			disk='sda'
                else
                        echo "ERROR: can't find disk mmcblk0 ok mmcblk1 or sda"
                        exit 1
                fi

                # get last partition
                part=$(grep  "${disk}p" /proc/partitions | tail -1 | awk '{print $4}' | xargs)
		# if no part found retry without p
                if [ -z "$part" ]; then
                        part=$(grep  "${disk}" /proc/partitions | tail -1 | awk '{print $4}' | xargs)
                fi
		# if still no part found exit
                if [ -z "$part" ]; then
                        echo "ERROR: can't find partition"
                        exit 1
                fi

                partN=$(echo $part | tail -c 2)  
                firstSec=$(parted /dev/${disk} 'unit s print' | grep "^ $partN" | awk '{print $2}')
                firstSec=${firstSec::-1}  

                # fdisk: delete and recreate the last partition with the largest size possible.
                (
                echo d # Delete partition
                echo $partN # Last partition
                echo n # Add a new partition
                echo p # Primary partition
                echo $partN # Last partition
                echo $firstSec # First sector 
                echo           # Last sector (Accept default: varies)
                echo Y # confirm existing signature 
                echo w # Write changes
                ) | fdisk /dev/$disk 

                resize2fs /dev/$part

                # Put Flair to inform other modules
                touch /tmp/new-drive
fi
