#!/bin/bash

if [ "$#" -eq  "0" ]; then
 	name=rastapi-unknown
else
 	name=$1
fi

echo "[hostrename] Setting name: $name"

current=$(cat /etc/hostname)
if [[ $current == $name ]]; then
	echo "[hostrename] hostname already set as $name"
	exit 0
fi
	
rw

systemctl restart systemd-hostnamed
sed -i -E 's/^127.0.1.1.*/127.0.1.1\t'"$name"'/' /etc/hosts
for file in /boot/wifi/*-hotspot.nmconnection /boot/wifi/_disabled/*-hotspot.nmconnection; do
	if [ -f "$file" ]; then
		sed -i -E 's/^ssid=.*/ssid='"$name"'/' "$file"
		echo "updated $(basename "$file") name"
	fi
done

# try hostnamectl set-hostname first, if it fails, fallback to manual edit

hostnamectl set-hostname "$name"
sync

current=$(cat /etc/hostname)
if [[ $current != $name ]]; then
	echo "[hostrename] hostnamectl failed, trying manual edit"
	echo "$name" > /etc/hostname
fi
sync

systemctl restart avahi-daemon
setnet
ro

current=$(cat /etc/hostname)
if [[ $current != $name ]]; then
	echo "[hostrename] hostname change failed, current: $current, expected: $name"
	exit 1
fi

echo "[hostrename] hostname changed to $name"    
exit 0