#!/bin/bash

if [ "$#" -eq  "0" ]; then
 	name=rastapi-unknown
else
 	name=$1
fi

echo "[hostrename] Setting name: $name"

if [[ $(hostnamectl hostname) != "$name" ]]; then
	rw
	sed -i -E 's/^127.0.1.1.*/127.0.1.1\t'"$name"'/' /etc/hosts
	for file in /boot/wifi/*-hotspot.nmconnection; do
		if [ -f "$file" ]; then
			sed -i -E 's/^ssid=.*/ssid='"$name"'/' "$file"
			echo "updated $(basename "$file") name"
		fi
	done
	hostnamectl hostname "$name"
	sync
	systemctl restart avahi-daemon
	setnet
	ro
	echo "[hostrename] hostname changed to $name"    
else
	echo "[hostrename] hostname already set as $name"    
fi
