#!/bin/bash

# interactive only (prevent start over ssh)
# [[ $- != *i* ]] && return

DIR="$(dirname "$(readlink -f "$0")")"


#
# DEFAULT CONFIG
#
URL="https://hemisphere-project.com"
ROTATE="0"      # 0, 90, 180, 270
REFLECT="n"     # n, x   (y, xy not supported)


#
# CMD LINE OVERWRITE
#
while [[ $# -gt 0 ]]; do
  case $1 in
    -u|--url)
      URL="$2"
      shift # past argument
      shift # past value
      ;;
    -r|--rotate)
      ROTATE="$2"
      shift # past argument
      shift # past value
      ;;
    -m|--reflect)
      REFLECT="$2"
      shift # past argument
      shift # past value
      ;;
    *)
      echo "Unknown argument $1"
      exit 1
      ;;
  esac
done
# echo $URL
# echo $ROTATE
# exit 0

TRANSFORM="normal"
if [ "$ROTATE" == "90" ]; then
  TRANSFORM="rotate-90"
elif [ "$ROTATE" == "180" ]; then
  TRANSFORM="rotate-180"
elif [ "$ROTATE" == "270" ]; then
  TRANSFORM="rotate-270"
fi

if [ "$REFLECT" == "x" ]; then
  if [ "$TRANSFORM" == "normal" ]; then
    TRANSFORM="flipped"
  else 
    TRANSFORM="flipped-$TRANSFORM"
  fi
fi

#
# COG Launcher
#
COGLAUNCHER="/tmp/cog-launcher"
echo "#!/usr/bin/env sh
cog \
  --media-playback-requires-user-gesture=0 \
  --set-permissions=all \
  --enable-webgl=1 \
  --enable-webaudio=1 \
  --webprocess-failure=exit \
  --allow-universal-access-from-file-urls=1 \
  file://${DIR}/loader.html#${URL}
" > $COGLAUNCHER
chmod +x $COGLAUNCHER

#
# WESTON settings
#
export KIOSK_WIDTH="$(cat /sys/class/graphics/fb0/virtual_size | cut -d',' -f1)"
export KIOSK_HEIGHT="$(cat /sys/class/graphics/fb0/virtual_size | cut -d',' -f2)"
export COG_PLATFORM_WL_VIEW_FULLSCREEN=1
export GTK_THEME="Adwaita:dark"

# FIND FIRST ENABLED HDMI OUTPUT (default to first one)
NAME=$(ls /sys/class/drm | grep HDMI -m1)
for OUTPUT in $(ls /sys/class/drm | grep HDMI); do
  echo $(cat /sys/devices/platform/gpu/drm/${OUTPUT:0:5}/$OUTPUT/enabled) $OUTPUT 
  if [ "$(cat /sys/devices/platform/gpu/drm/${OUTPUT:0:5}/$OUTPUT/enabled)" == "enabled" ]; then
    NAME=$OUTPUT
    break
  fi
done


# PREPARE WESTON CONFIG
WESTONCONF="
[core]
idle-time=0
repaint-window=15
require-input=false

[shell]
client=$COGLAUNCHER
animation=none
close-animation=none
startup-animation=none
locking=false

[output]
name=${NAME:6}
mode=${KIOSK_WIDTH}x${KIOSK_HEIGHT}     
transform=${ROTATE}

[input-method]
path=/usr/lib/<wrong-path>/weston-keyboard  # wrong path -> disable virtual keyboard
"

#INFO
echo " "
echo ".:: HKiosk ::."
echo " "
echo "WESTON CONFIG"
echo "Resolution: $KIOSK_WIDTH x $KIOSK_HEIGHT"
echo "HDMI out: ${NAME:6}"
echo " "
echo "COG LAUNCHER"
echo "$COGLAUNCHER"
echo " "

# START WESTON
if [[ -z $DISPLAY && $XDG_VTNR -eq 1 ]] && [ "$(pgrep --list-name weston)" = "" ] 
then

  echo "$WESTONCONF" > ~/.config/weston.ini
  weston

else
  
  echo "$WESTONCONF" >  /tmp/weston.ini


  export XDG_RUNTIME_DIR=/run/user/1000
  export XDG_CACHE_HOME=/tmp
  export XDG_DATA_HOME=/tmp
  export DBUS_SESSION_BUS_ADDRESS=unix:path=/run/user/1000/dbus/user_bus_socket
  /bin/mkdir -p /run/user/1000/dbus

  weston --tty 1 -c /tmp/weston.ini
fi
