#! /usr/bin/env bash

THISFILE="$0"
STATEFILE="/data/var/fake-clock.state"

saveclock() {
    echo "Saving current time to $STATEFILE"
    touch "$STATEFILE"
}

loadclock() {
    local savedtime=$(stat -c %Y "$STATEFILE")
    if [ $(date +%s) -lt $savedtime ]; then
        echo "Restoring saved system time from $STATEFILE"
        date -s @$savedtime
    else
        echo "Saved time is older than current time, saving new time"
        saveclock
    fi
}

case "$1" in
    load)
        loadclock
        ;;
    set)
        echo "'set' is deprecated, use 'load' instead."
        echo "Consider using the systemd timer unit fake-hwclock-save.timer"
        loadclock
        ;;
    save)
        saveclock
        ;;
    *)
        echo "Usage: $THISFILE {load|save}"
        exit 1
        ;;
esac