#!/bin/bash
# systemctl daemon-reload
sync

# Remount root filesystem as read-only, retry 10 times
for i in {1..10}; do
    echo "Attempt $i:"
    mount -o remount,ro /
    if touch /root/testfile 2>/dev/null; then
        echo "Failed.. still able to touch file, trying again..."
        # lsof / | grep -E '(w|u)'
        sleep 1  # Wait a second before the next attempt
    else
        echo "Success! system is now read-only."
        break
    fi
done

if (lsblk -o uuid /dev/mmcblk0p3 > /dev/null 2>&1); then
    mount -o remount,ro /boot/firmware 
elif (lsblk -o uuid /dev/mmcblk1p8 > /dev/null 2>&1); then
    mount -o remount,ro /boot/efi 
fi
sync
echo "=> RO"
