#!/bin/bash

# Disable any form of screen saver / screen blanking / power management
xset s off
xset s noblank
xset -dpms

POINTER_XID=$(xinput -list | grep "pointer" | grep -v vc4 | grep -v "Virtual" | cut -f 2 | cut -d "=" -f 2)
echo "POINTER_XID: $POINTER_XID"


# Configure multi-monitor layout (extended mode)
xrandr --auto
connected_outputs=$(xrandr | grep " connected" | cut -d' ' -f1)
if [ $(echo "$connected_outputs" | wc -l) -gt 1 ]; then
    xrandr --output $(echo "$connected_outputs" | head -1) --auto --primary
    for display in $(echo "$connected_outputs" | tail -n +2); do
        xrandr --output $display --auto --right-of $(echo "$connected_outputs" | head -1)
    done
fi

# Rotate the screen if specified
XROTATE=${XROTATE:-"0"}
if [ "$XROTATE" != "0" ]; then
    case $XROTATE in
        90)
            xrandr --output $(xrandr | grep " connected" | cut -d' ' -f1 | head -1) --rotate right
            ;;
        180)
            xrandr --output $(xrandr | grep " connected" | cut -d' ' -f1 | head -1) --rotate inverted
            ;;
        270)
            xrandr --output $(xrandr | grep " connected" | cut -d' ' -f1 | head -1) --rotate left
            ;;
        *)
            xrandr --output $(xrandr | grep " connected" | cut -d' ' -f1 | head -1) --rotate normal
            ;;
    esac
fi

# Flip the screen if specified
XREFLECT=${XREFLECT:-"n"}
if [ "$XREFLECT" != "n" ]; then
    case $XREFLECT in
        x)
            xrandr --output $(xrandr | grep " connected" | cut -d' ' -f1 | head -1) --reflect x
            ;;
        y)
            xrandr --output $(xrandr | grep " connected" | cut -d' ' -f1 | head -1) --reflect y
            ;;
        xy)
            xrandr --output $(xrandr | grep " connected" | cut -d' ' -f1 | head -1) --reflect xy
            ;;
        *)
            xrandr --output $(xrandr | grep " connected" | cut -d' ' -f1 | head -1) --reflect none
            ;;
    esac
fi

# Pointer to the primary output
if [ -n "$POINTER_XID" ]; then
    xinput --map-to-output $POINTER_XID $(xrandr | grep " connected" | cut -d' ' -f1 | head -1)
fi

# Allow quitting the X server with CTRL-ATL-Backspace
setxkbmap -option terminate:ctrl_alt_bksp

xrandr
# Start applications (customize as needed)
# chromium --kiosk "http://your-url" &
# mpv --fs /path/to/video &