#!/bin/bash
# Start X session as 'hmini' with tmpfs Xauthority
export XAUTHORITY=/tmp/.Xauthority
chmod 777 /tmp
touch $XAUTHORITY
chown hmini:hmini $XAUTHORITY

# Start LightDM 
systemctl unmask lightdm.service
systemctl start lightdm.service

# Start Openbox session directly without LightDM
# USER=hmini
# export XAUTHORITY=/tmp/.Xauthority
# sudo -u $USER XAUTHORITY=$XAUTHORITY startx /usr/bin/openbox-session -- :0