#!/usr/bin/env python3
import os, time, syslog
import subprocess

TAG = 'splash'
syslog.openlog(TAG)

def log(msg):
    print(f"[{TAG}] {msg}")
    syslog.syslog(syslog.LOG_INFO, msg)

dir = os.path.dirname(os.path.realpath(__file__))

log("Displaying splash screen")
p = subprocess.Popen( ('fbi -d /dev/fb0 --noverbose -a '+os.path.join(dir, 'splash.png')).split(' ') )
time.sleep(5)
p.kill()
p = subprocess.Popen( ('fbi -d /dev/fb0 --noverbose -a '+os.path.join(dir, 'black.png')).split(' ') )
# Keep the script running so the black screen stays displayed
p.wait()
